# Generated by Django 5.2 on 2025-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="images/default_photo.png", upload_to="images/"
            ),
        ),
    ]
