# Generated by Django 5.2 on 2025-04-07 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
