# Generated by Django 5.2 on 2025-04-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cart_created_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="session_key",
        ),
    ]
