# Generated by Django 5.0.9 on 2025-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
